# Generated by Django 5.0.1 on 2024-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='codeforces_username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='leetcode_username',
            field=models.CharField(max_length=100),
        ),
    ]
