# Generated by Django 5.0.1 on 2024-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_student_codeforces_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='codeforces_solved_problems_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='leetcode_solved_problems_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
